be_words = [ 'am', 'is', 'are', 'been', 'being', 'was', 'were' ]
mod_words = ['can', 'could', 'shall', 'should', 'will', 'would', 'may', 'might','do', 'did', 'does', 'have', 'had', 'has' ]
mid_sentence_wh_questions = ['what','when','why','where','how']
indirect_quest = ['can', 'could','will', 'would','may']
custom_stop_words = [
    "a", "about", "above", "across", "after", "afterwards", "again", "against",
    "all", "almost", "alone", "along", "already", "also", "although", "always",
     "among", "amongst", "amoungst", "amount", "an", "and", "another",
    "any", "anyhow", "anything", "anyway", "anywhere", 
    "around", "as", "at", "back", "became", "because", "become",
    "becomes", "becoming", "before", "beforehand", "behind",
    "below", "beside", "besides", "between", "beyond", "bill", "both",
    "bottom", "but", "by", "call", "cannot", "co", "con", "couldnt", "cry", "de", "describe", "detail", "done",
    "down", "due", "during", "each", "eg", "eight", "either", "eleven", "else",
    "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone",
    "everything", "everywhere", "except", "few", "fifteen", "fifty", "fill",
    "find", "fire", "first", "five", "for", "former", "formerly", "forty",
    "found", "four", "from", "front", "full", "further", "get", "give", "go",
    "he", "hence", "her", "here", "hereafter",
    "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his",
    "how", "however", "hundred", "i", "ie", "if", "in", "inc", "indeed",
    "interest", "into", "it", "its", "itself", "keep", "last", "latter",
    "latterly", "least", "less", "ltd", "made", "many", "me",
    "meanwhile", "mill", "mine", "more", "moreover", "most", "mostly",
    "move", "much", "must", "my", "myself", "name", "namely", "neither",
    "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone",
    "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on",
    "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our",
    "ours", "ourselves", "out", "over", "own", "part", "per", "perhaps",
    "please", "put", "rather", "re", "same", "see", "seem", "seemed",
    "seeming", "seems", "serious", "several", "she", "show", "side",
    "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone",
    "something", "sometime", "sometimes", "somewhere", "still", "such",
    "system", "take", "ten", "than", "that", "the", "their", "them",
    "themselves", "then", "thence", "there", "thereafter", "thereby",
    "therefore", "therein", "thereupon", "these", "they", "thick", "thin",
    "third", "this", "those", "though", "three", "through", "throughout",
    "thru", "thus", "to", "together", "too", "top", "toward", "towards",
    "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us",
    "very", "via", "we", "well",
    "whence", "whereafter", "whereas", "whereby",
    "wherein", "whereupon", "wherever", "whither", "whoever", "whole", "with",
    "within", "without", "yet", "you", "your", "yours", "yourself",
    "yourselves"]